baseURL = "https://hardcore-dubinsky-5db000.netlify.com/"
languageCode = "en-us"
title = "Hugo preflight demo"
theme = "qnorr"
SectionPagesMenu = "main"

[params]
  test = "testing global"

[permalinks]
  # blog = "/:year/:month/:slug/"